# Model
device: 0
model_parallel: true
gpu_used_id: [0, 1, 2] # [0, 1, 2]
gpu_split: ['layers.6', 'layers.19']
task: comprehendedit # vqa, comprehendedit

name: /home/myh/hugging_cache/Vicuna-7b1
model_name: minigpt4
model_class: Blip2OPT
small_name: /home/myh/hugging_cache/Vicuna-7b1
tokenizer_class: LlamaTokenizer
tokenizer_name: /home/myh/hugging_cache/Vicuna-7b1
cls_name: /home/myh/hugging_cache/distilbert-base-cased
cls_class: AutoModel
sentence_model_name: /home/myh/hugging_cache/all-MiniLM-L6-v2
inner_params:
- llama_model.model.layers.29.mlp.down_proj.weight
- llama_model.model.layers.29.mlp.up_proj.weight
- llama_model.model.layers.30.mlp.down_proj.weight
- llama_model.model.layers.30.mlp.up_proj.weight
- llama_model.model.layers.31.mlp.down_proj.weight
- llama_model.model.layers.31.mlp.up_proj.weight

# Method
alg: HICE
lr: 1e-5
edit_lr: 1e-2
seed: 0
lr_lr: 0.0
cedit: 0.1
iedit: 0.1
cloc: 1.0
cbase: 1.0
dropout: 0.0
final_eval: True
supervised: False
train_base: False
no_grad_layers: null
soft_weighting: False
checkpoint_grad: False
cross_attend: False
cos: False
freeze: null
square: True
bound_embeds: False
use_all_negatives: False
freeze_cntr: False
dist_heads: 1
lora: null
archive: null

batch_size: 1
model_save_pt: 5000
edit_bs: 1
silent: False
#max_epochs: 1
max_iters: 20000
log_interval: 100
val_interval: 5000
early_stop_patience: 30000
early_stop_key: "loss/total_edit_val"
eval_only: False
half: False
save: False
debug: False
log_errors: False
unlikelihood: True

val_batch_size: 1
accumulate_bs: 1
val_steps: 1000
opt: Adam
grad_clip: 100.

# Output
results_dir: ./results

# Multimodal
exact_match: True
qformer_checkpoint: /home/myh/hugging_cache/blip2_pretrained_flant5xxl.pth
qformer_name_or_path: /home/myh/hugging_cache/bert-base-uncased
state_dict_file: /home/myh/hugging_cache/eva_vit_g.pth
pretrained_ckpt: /home/myh/hugging_cache/pretrained_minigpt4_7b.pth

# image
coco_image: /home/myh/Datasets/MMEdit
rephrase_image: /home/myh/Datasets/MMEdit
